"""Test that character slot processing prevents duplicate pregenerated characters."""

import pytest
from unittest.mock import Mock, MagicMock, patch
from gaia.api.routes.campaigns import CampaignService, CharacterSlotRequest


@pytest.fixture
def campaign_service():
    """Create a campaign service with test character isolation."""
    from gaia.utils.singleton import SingletonMeta
    from gaia.api.routes.campaign_generation import PreGeneratedContent

    # Reset singleton completely before test to avoid pollution from other tests
    SingletonMeta._instances.pop(PreGeneratedContent, None)

    # Patch _load_content to prevent loading real data from disk
    with patch.object(PreGeneratedContent, '_load_content'):
        mock_orchestrator = Mock()
        mock_orchestrator.campaign_manager = Mock()
        service = CampaignService(mock_orchestrator)

        # Initialize with empty lists to avoid loading real data
        service.pregen_content.characters = []
        service.pregen_content.campaigns = []

        yield service

    # Teardown: reset singleton again after test
    SingletonMeta._instances.pop(PreGeneratedContent, None)


def test_character_slot_deduplication(campaign_service):
    """Test that multiple autogenerated slots don't select the same character."""
    # Set up test characters (fixture will restore original after test)
    campaign_service.pregen_content.characters = [
        {"name": "Character 1", "character_class": "Fighter"},
        {"name": "Character 2", "character_class": "Wizard"},
        {"name": "Character 3", "character_class": "Rogue"},
        {"name": "Character 4", "character_class": "Cleric"},
    ]

    # Create 4 character slots, all using pregenerated characters
    character_slots = [
        CharacterSlotRequest(slot_id=1, use_pregenerated=True, character_data=None),
        CharacterSlotRequest(slot_id=2, use_pregenerated=True, character_data=None),
        CharacterSlotRequest(slot_id=3, use_pregenerated=True, character_data=None),
        CharacterSlotRequest(slot_id=4, use_pregenerated=True, character_data=None),
    ]

    # Process the character slots
    result = campaign_service._process_character_slots(character_slots)

    # Verify we got 4 characters
    assert len(result) == 4, f"Expected 4 characters, got {len(result)}"

    # Verify all characters are unique
    character_names = [char.get('name') for char in result]
    unique_names = set(character_names)

    assert len(unique_names) == 4, f"Expected 4 unique characters, got {len(unique_names)}: {character_names}"
    print(f"✅ All 4 characters are unique: {character_names}")


def test_character_slot_with_provided_data_prevents_duplicates(campaign_service):
    """Test that provided character data is tracked to prevent duplicates in subsequent slots."""
    # Set up test characters (fixture will restore original after test)
    campaign_service.pregen_content.characters = [
        {"name": "Character 1", "character_class": "Fighter"},
        {"name": "Character 2", "character_class": "Wizard"},
        {"name": "Character 3", "character_class": "Rogue"},
    ]

    # First slot uses a specific character, second slot autogenerates
    character_slots = [
        CharacterSlotRequest(
            slot_id=1,
            use_pregenerated=True,
            character_data={"name": "Character 1", "character_class": "Fighter"}
        ),
        CharacterSlotRequest(slot_id=2, use_pregenerated=True, character_data=None),
        CharacterSlotRequest(slot_id=3, use_pregenerated=True, character_data=None),
    ]

    # Process the character slots
    result = campaign_service._process_character_slots(character_slots)

    # Verify we got 3 characters
    assert len(result) == 3, f"Expected 3 characters, got {len(result)}"

    # Verify all characters are unique
    character_names = [char.get('name') for char in result]
    unique_names = set(character_names)

    assert len(unique_names) == 3, f"Expected 3 unique characters, got {len(unique_names)}: {character_names}"

    # Verify the first character is the one we provided
    assert result[0].get('name') == "Character 1", f"First character should be 'Character 1', got '{result[0].get('name')}'"

    # Verify the second and third characters are different from the first
    assert result[1].get('name') != "Character 1", f"Second character should not be 'Character 1'"
    assert result[2].get('name') != "Character 1", f"Third character should not be 'Character 1'"

    print(f"✅ All 3 characters are unique: {character_names}")
    print(f"✅ First slot used provided character, others autogenerated without duplicates")


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
