"""Pydantic schemas for session sharing and membership APIs."""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field, ConfigDict


class SessionShareRequest(BaseModel):
    """Request payload for creating or regenerating a session invite."""

    session_id: str = Field(..., description="Session identifier to share")
    regenerate: bool = Field(
        default=False,
        description="When True, invalidate existing invite tokens before creating a new one",
    )
    expires_in_minutes: Optional[int] = Field(
        default=None,
        ge=1,
        le=7 * 24 * 60,
        description="Optional expiration window for the invite token",
    )
    multi_use: bool = Field(
        default=True,
        description="When True, the invite token can be used multiple times",
    )
    max_uses: Optional[int] = Field(
        default=None,
        ge=1,
        description="Optional cap on number of uses when multi_use is enabled",
    )


class SessionShareResponse(BaseModel):
    """Response payload containing a shareable invite token."""

    success: bool = Field(default=True)
    session_id: str
    invite_token: str
    expires_at: Optional[datetime] = None

    model_config = ConfigDict(json_encoders={datetime: lambda v: v.isoformat()})


class SessionJoinRequest(BaseModel):
    """Request payload for joining a session via invite token."""

    invite_token: str = Field(..., description="Invite token generated by session owner")


class SessionJoinResponse(BaseModel):
    """Response payload after successfully joining a session."""

    success: bool = Field(default=True)
    session_id: str
